spring:
  datasource:
    url: jdbc:mysql://49.50.162.100:3306/rualone_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: {id}
    password: { password }
  jpa:
    hibernate:
      ddl-auto: create