spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rualone_local?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: rualone
    password: rualone
  jpa:
    hibernate:
      ddl-auto: none
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always