spring:
  config:
    import: "optional:configserver:https://config.rualone.site/" #config server uri
  cloud:
    config:
      name: application #참고하고자 하는 yml 파일의 이름 앞부분
      profile: test #참고하고자 하는 yml 파일의 이름 뒷부분 (실제 파일에서 -로 구분됌)
encrypt:
  key: